baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'nyhil'
enableGitInfo = true
[frontmatter]
    lastmod = [':fileModTime', ':default']
[params]
    subtitle = 'look at you, hacker.'
    subtitleTag = "you're it"
    dateFormat = '2006-01-02'
[markup]
    defaultMarkdownHandler = 'org'
    [markup.highlight]
        lineNos = true
        noClasses = false
